services:
  postgres:
    image: postgres:14
    container_name: infra-postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: sandeidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret_password
    volumes:
      - mongodata:/data/db
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "secret_password"]
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a secret_password ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ../backend
    env_file:
      - ../backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  ia-service:
    build: ../ia-service
    env_file:
      - ../ia-service/.env
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend-net

  frontend:
    build: ../frontend
    env_file:
      - ../frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  pgdata:
  mongodata:
  rabbitmqdata:
