name: IA Service CI/CD

on:
  push:
    branches: [main, dev]
    paths:
      - 'ia-service/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'ia-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ia-service
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Set up venv
        run: python -m venv venv
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install flake8 pytest uvicorn
      - name: Lint
        run: |
          source venv/bin/activate
          flake8 app
      - name: Test
        run: |
          source venv/bin/activate
          pytest
      - name: Uvicorn dry run
        run: |
          source venv/bin/activate
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          pid=$!
          sleep 5
          kill $pid
      - name: Build Docker image
        run: |
          docker build -t ia-service:test .
          docker run --rm ia-service:test python -c "import sys;print(sys.version)"
      # - name: Push image
      #   run: docker push <registry>/ia-service:test
